# The URL the site will be built for
base_url = "/"

title = "RustHDL - a framework for writing strongly typed firmware in Rust."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Configuration of the Markdown rendering
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "inspired-github"

[extra]
juice_logo_name = "RustHDL"
juice_logo_path = "juice.svg"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/samitbasu/rust-hdl" }
]
repository_url = "https://github.com/samitbasu/rust-hdl"